# Generated by Django 5.0.6 on 2024-06-10 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CertificacionesParcialesApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foliosequencecp',
            name='letra',
            field=models.CharField(default='A', max_length=1),
        ),
    ]
