# Generated by Django 5.0.6 on 2024-06-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CertificacionesParcialesApp', '0002_foliosequencecp_letra'),
    ]

    operations = [
        migrations.CreateModel(
            name='FolioLetraCP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letra', models.CharField(default='A', max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='foliosequencecp',
            name='letra',
        ),
    ]
