# Generated by Django 5.0.6 on 2024-07-31 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConfiguracionApp', '0002_autoridadeducativa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bachillerato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
    ]
